services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-frontend
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5174:5174"
    networks:
      - pokemonnetwork
    command: npm run dev -- --port 5174 --host

networks:
  pokemonnetwork:
    driver: bridge
